config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  apipie

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}, path: '/users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'join'}

  namespace :api do
    namespace :v1 do
      resources :location_types, only: [:index, :show]
      resources :machine_conditions, only: [:destroy]
      resources :machine_score_xrefs, only: [:create, :show]
      resources :machines, only: [:index, :show, :create]
      resources :operators, only: [:index, :show]

      resources :user_submissions, only: [:list_within_range, :location, :total_user_submission_count] do
        collection do
          get :list_within_range
          get :location
          get :total_user_submission_count
          get :top_users
        end
      end

      resources :users, only: [:auth_details, :total_user_count] do
        member do
          post :add_fave_location
          get  :list_fave_locations
          get  :profile_info
          post :remove_fave_location
        end
        collection do
          get :total_user_count
          get  :auth_details
          post :signup
          post :forgot_password
          post :resend_confirmation
        end
      end
      resources :regions, only: [:index, :show] do
        collection do
          get  :closest_by_lat_lon
          get  :does_region_exist
          get  :location_and_machine_counts
          post :suggest
          post :contact
          post :app_comment
        end
      end
      resources :location_machine_xrefs, only: [:create, :destroy, :update, :show] do
        put :ic_toggle
        collection do
          get :top_n_machines
        end
      end
      resources :locations, only: [:index, :show, :update] do
        member do
          get :machine_details
          put :confirm
        end
        collection do
          get :closest_by_lat_lon
          get :closest_by_address
          get :within_bounding_box
          get :autocomplete
          get :autocomplete_city
          get :top_cities
          get :top_cities_by_machine
          get :type_count
          post :suggest
        end
      end

      scope 'region/:region', constraints: lambda { |request| Region.where('lower(name) = ?', request[:region].downcase).any? } do
        resources :events, only: [:index, :show]
        resources :location_machine_xrefs, only: [:index]
        resources :locations, only: [:index, :show]
        resources :machine_score_xrefs, only: [:index, :show]
        resources :operators, only: [:index]
        resources :region_link_xrefs, only: [:index, :show]
        resources :user_submissions, only: [:index, :show]
        resources :zones, only: [:index, :show]
      end
    end
  end

  get '/app' => 'pages#app'
  get '/app/support' => 'pages#app_support'
  get '/privacy' => 'pages#privacy'
  get '/faq' => 'pages#faq'
  get '/store' => 'pages#store'
  get '/donate' => 'pages#donate'
  get '.well-known/apple-app-site-association' => 'pages#apple_app_site_association'

  scope ':region', constraints: lambda { |request| Region.where('lower(name) = ?', request[:region].downcase).any? } do
    get 'app' => redirect('/app')
    get 'app/support' => redirect('/app/support')
    get 'privacy' => redirect('/privacy')
    get 'faq' => redirect('/faq')
    get 'store' => redirect('/store')
    get 'donate' => redirect('/donate')

    resources :events, only: [:index, :show]
    resources :regions, only: [:index, :show]
    resources :location_machine_xrefs, only: [:index], format: 'rss', :as => :lmx_rss
    resources :machine_score_xrefs, only: [:index], format: 'rss', :as => :msx_rss

    resources :pages

    # xml/rss mismatch to support rss-formatted output with $region.xml urls, $region.rss is already expected by mobile devices, and is expected to be formatted without hrefs
    get ':region' + '.xml' => 'location_machine_xrefs#index', format: 'rss'

    get ':region' + '.rss' => 'location_machine_xrefs#index', format: 'xml'
    get ':region' + '_scores.rss' => 'machine_score_xrefs#index', format: 'xml'
    get '/robots.txt', to: 'pages#robots'

    get '/' => 'pages#region', as: 'region_homepage'
    get '/about' => 'pages#about'
    get '/contact' => 'pages#contact'
    post '/contact_sent' => 'pages#contact_sent'
    get '/links' => 'pages#links'
    get '/high_rollers' => 'pages#high_rollers'
    get '/suggest' => 'pages#suggest_new_location'
    post '/submitted_new_location' => 'pages#submitted_new_location'
    get '/flier' => 'pages#flier'

    get 'all_region_data.json', to: 'regions#all_region_data', format: 'json'

    get '*page', to: 'locations#unknown_route'
  end

  resources :locations, only: [:index, :show] do
    collection do
      get :update_metadata
      get :autocomplete
      get :autocomplete_city
    end
    member do
      get :confirm
      get :locations_for_machine
      get :newest_machine_name
      get :render_add_machine
      get :render_update_metadata
      get :render_machine_names_for_infowindow
      get :render_machines_count
      get :render_last_updated
      get :render_location_detail
      get :render_machines
      get :render_scores
    end
  end

  resources :machines, only: [:index, :show] do
    collection do
      get :autocomplete
    end
  end

  resources :location_machine_xrefs do
    collection do
      get :update_machine_condition
    end
    member do
      get :condition_update_confirmation
      get :create_confirmation
      get :remove_confirmation
      get :render_machine_conditions
      patch :ic_toggle
    end
  end

  resources :machine_score_xrefs
  resources :location_picture_xrefs
  resources :machine_conditions
  resources :suggested_locations, only: [] do
      member do
        post :convert_to_location
      end
  end

  resources :users, only: [:profile, :fave_locations, :toggle_fave_location] do
    member do
      get :profile, :fave_locations
      post :toggle_fave_location
    end
  end

  get 'inspire_profile' => 'pages#inspire_profile'
  get 'pages/home'
  get 'map' => 'pages#map'
  get 'saved' => 'pages#map', user_faved: true
  get 'map_location_data' => 'pages#map_location_data'
  get 'suggest' => 'pages#suggest_new_location', as: 'map_location_suggest'
  post 'submitted_new_location' => 'pages#submitted_new_location', as: 'map_submitted_new_location'
  get 'flier' => 'pages#flier', as: 'map_flier'

  # legacy names for regions
  get '/milwaukee' => redirect('/wisconsin')
  get '/regionless' => redirect('/map')
  get '/central-indiana' => redirect('/indiana')
  get '/mid-michigan' => redirect('/map')
  get '/burlington' => redirect('/vermont')
  get '/apps' => redirect('/app')
  get '/apps/support' => redirect('/app/support')
  get '/profile' => redirect('/inspire_profile')
  get '/twincities' => redirect('/minnesota')
  get '/maryland-north' => redirect('/baltimore')
  get '/portland-maine' => redirect('/maine')
  get '/orlando' => redirect('/florida-central')
  get '/london' => redirect('/uk')
  get '/chico' => redirect('/map')
  get '/michigan-west' => redirect('/michigan-sw')
  get '/michigan-mid' => redirect('/michigan-north')
  get '/roanoke' => redirect('/map')
  get '/redding' => redirect('/map')

  root to: 'pages#home'
end

app/controllers/api/v1/location_machine_xrefs_controller.rb
module Api
  module V1
    class LocationMachineXrefsController < InheritedResources::Base
      skip_before_action :verify_authenticity_token

      before_action :allow_cors
      respond_to :json
      has_scope :region, :limit

      DEFAULT_TOP_N_MACHINES = 25

      api :GET, '/api/v1/region/:region/location_machine_xrefs.json', 'Get all machines at locations in a single region'
      param :region, String, desc: 'Name of the Region you want to see events for', required: true
      param :limit, Integer, desc: 'Limit the number of results that are returned', required: false
      formats ['json']
      def index
        lmxes = apply_scopes(LocationMachineXref).order('location_machine_xrefs.id desc').includes(:location, :machine, machine_conditions: :user).order('machine_conditions.created_at desc')
        return_response(lmxes, 'location_machine_xrefs', %i[location machine machine_conditions])
      end

      api :GET, '/api/v1/location_machine_xrefs/:id.json', 'Get info about a single lmx'
      param :id, Integer, desc: 'LMX id', required: true
      formats ['json']
      def show
        lmx = LocationMachineXref.find(params[:id])
        return_response(lmx, 'location_machine', [], %i[last_updated_by_username machine_conditions])
      end

      api :POST, '/api/v1/location_machine_xrefs.json', 'Find or create a machine at a location'
      param :location_id, Integer, desc: 'Location ID to add machine to', required: true
      param :machine_id, Integer, desc: 'Machine ID to add to location', required: true
      param :condition, String, desc: "Notes on machine's condition", required: false
      formats ['json']
      def create
        user = current_user.nil? ? nil : current_user

        return return_response(AUTH_REQUIRED_MSG, 'errors') if user.nil?

        location_id = params[:location_id]
        machine_id = params[:machine_id]
        condition = params[:condition]
        status_code = 200

        return return_response('Failed to find machine', 'errors') if machine_id.nil? || location_id.nil? || !Machine.exists?(machine_id) || !Location.exists?(location_id)

        lmx = LocationMachineXref.find_by_location_id_and_machine_id(location_id, machine_id)

        if lmx.nil?
          status_code = 201
          lmx = LocationMachineXref.create(location_id: location_id, machine_id: machine_id, user_id: user&.id)
        end

        if condition
          lmx.update_condition(
            condition,
            remote_ip: request.remote_ip,
            request_host: request.host,
            user_agent: request.user_agent,
            user_id: user&.id
          )
        end

        return_response(lmx, 'location_machine', [], [:last_updated_by_username], status_code)
      end

      api :PUT, '/api/v1/location_machine_xrefs/:id.json', "Update a machine's condition at a location"
      param :id, Integer, desc: 'LMX id', required: true
      param :condition, String, desc: "Notes on machine's condition", required: true
      formats ['json']
      def update
        lmx = LocationMachineXref.find(params[:id])
        user = current_user.nil? ? nil : current_user

        return return_response(AUTH_REQUIRED_MSG, 'errors') if user.nil?

        lmx.update_condition(
          params[:condition],
          remote_ip: request.remote_ip,
          request_host: request.host,
          user_agent: request.user_agent,
          user_id: user&.id
        )

        return_response(lmx, 'location_machine', [], %i[last_updated_by_username machine_conditions])
      rescue ActiveRecord::RecordNotFound
        return_response('Failed to find machine', 'errors')
      end

      api :DESTROY, '/api/v1/location_machine_xrefs/:id.json', 'Remove a machine from a location'
      param :id, Integer, desc: 'LMX id', required: true
      formats ['json']
      def destroy
        lmx = LocationMachineXref.find(params[:id])
        user = current_user.nil? ? nil : current_user

        return return_response(AUTH_REQUIRED_MSG, 'errors') if user.nil?

        lmx.destroy(
          remote_ip: request.remote_ip,
          request_host: request.host,
          user_agent: request.user_agent,
          user_id: user&.id
        )

        return_response('Successfully deleted lmx #' + lmx.id.to_s, 'msg')
      rescue ActiveRecord::RecordNotFound
        return_response('Failed to find machine', 'errors')
      end

      api :GET, '/api/v1/location_machine_xrefs/top_n_machines.json', 'Show the top N machines on location'
      param :n, String, desc: 'Number of machines to show', required: false
      formats ['json']
      def top_n_machines
        top_n = params[:n] ||= DEFAULT_TOP_N_MACHINES

        records_array = ActiveRecord::Base.connection.exec_query(<<HERE).to_a
select
  left(m.opdb_id,5) as opdb_id,
  split_part(min(m.name), ' (', 1) as machine_name,
  (array_agg(m.manufacturer ORDER BY m.year ASC))[1] as manufacturer,
  min(m.year) as year,
  count(*) as machine_count
from
  location_machine_xrefs lmx inner join machines m on m.id=lmx.machine_id
group by 1
order by 5 desc
limit #{top_n}
HERE

        return_response(records_array, 'machines')
      end
    end
  end
end

app/controllers/location_machine_xrefs_controller.rb
class LocationMachineXrefsController < InheritedResources::Base
  respond_to :xml, :json, :html, :js, :rss
  has_scope :region
  before_action :authenticate_user!, only: %i[update_machine_condition create_confirmation remove_confirmation]

  def create
    machine = nil
    location = Location.find(params[:location_id])
    user = current_user.nil? ? nil : current_user

    if !params["add_machine_by_id_#{location.id}"].empty?
      machine = Machine.find(params["add_machine_by_id_#{location.id}"])
    elsif !params["add_machine_by_name_#{location.id}"].empty?
      machine = Machine.where(['lower(name) = ?', params["add_machine_by_name_#{location.id}"].downcase]).first

      if machine.nil?
        machine = Machine.new
        machine.name = params["add_machine_by_name_#{location.id}"]

        send_new_machine_notification(machine, location, user)
        return
      end
    else
      # blank submit
      return
    end

    location.date_last_updated = Date.today
    location.last_updated_by_user_id = user.id
    location.save(validate: false)

    LocationMachineXref.where(['location_id = ? and machine_id = ?', location.id, machine.id]).first ||
      LocationMachineXref.create(location_id: location.id, machine_id: machine.id, user_id: user.id)
  end

  def create_confirmation
    @lmx = LocationMachineXref.find(params[:id])
  end

  def destroy
    lmx = LocationMachineXref.find_by_id(params[:id])

    user_id = current_user&.id

    lmx.destroy(remote_ip: request.remote_ip, request_host: request.host, user_agent: request.user_agent, user_id: user_id) unless lmx&.nil?

    render nothing: true
  end

  def update_machine_condition
    id = params[:id]
    lmx = LocationMachineXref.find(id)

    condition = params["new_machine_condition_#{id}".to_sym]

    if condition.match?(/<a href/)
      lmx
    elsif ENV['RAKISMET_KEY']
      old_condition = lmx.condition

      lmx.condition = condition
      if lmx.spam?
        lmx.condition = old_condition
        nil
      else
        lmx.condition = old_condition
        lmx.update_condition(condition, remote_ip: request.remote_ip, request_host: request.host, user_agent: request.user_agent, user_id: current_user&.id)
        lmx.location.date_last_updated = Date.today
        lmx.location.last_updated_by_user_id = current_user&.id
        lmx.location.save(validate: false)
        lmx.location
      end
      lmx
    else
      lmx.update_condition(condition, remote_ip: request.remote_ip, request_host: request.host, user_agent: request.user_agent, user_id: current_user&.id)
      lmx.location.date_last_updated = Date.today
      lmx.location.last_updated_by_user_id = current_user&.id
      lmx.location.save(validate: false)
      lmx.location
      lmx
    end

    render nothing: true
  end

  def render_machine_conditions
    lmx = LocationMachineXref.find(params[:id])
    render partial: 'locations/render_machine_conditions', locals: { conditions: lmx.sorted_machine_conditions.includes([:user]), lmx: lmx }
  end

  def index
    @lmxs = apply_scopes(LocationMachineXref).order('location_machine_xrefs.id desc').limit(50).includes({ location: :region }, :machine, :user)
    respond_with(@lmxs)
  end

  def condition_update_confirmation; end

  def remove_confirmation; end

  private

  def event_params
    params.require(:location_machine_xref).permit(:machine_id, :location_id, :condition, :condition_date, :ip, :user_id)
  end
end

app/views/location_machine_xrefs/_ic_button.html.haml
- if lmx.ic_enabled?
  - has_text = "Has"
- else
  - has_text = "No"
- if !user_signed_in?
  = button_to new_user_session_path, :class => ["bold pointer ic_button", (lmx.ic_enabled == nil ? "ic_button_unknown_#{lmx.id} ic_unknown" : lmx.ic_enabled ? "ic_yes ic_button_#{lmx.id}" : "ic_no ic_button_#{lmx.id}")] do
    Insider Connected
- else
  = button_to ic_toggle_location_machine_xref_path(lmx), method: :patch, remote: :true, :class => ["bold pointer ic_button", (lmx.ic_enabled == nil ? "ic_button_unknown_#{lmx.id} ic_unknown" : lmx.ic_enabled ? "ic_yes ic_button_#{lmx.id}" : "ic_no ic_button_#{lmx.id}")] do
    Insider Connected

  :javascript
    $(".ic_button_unknown_#{lmx.id}").click(function(event){
      if (event.target.classList.contains('ic_unknown')) {
        $(this).removeClass("ic_unknown").addClass("ic_yes");
      } else {
        $(this).toggleClass("ic_no ic_yes");
      }
    })
    $(".ic_button_#{lmx.id}").click(function(){
      $(".ic_button_#{lmx.id}").toggleClass('ic_yes ic_no');
    });

app/views/location_machine_xrefs/_ipdb.html.haml
.external_machine_link
  - if (lmx.machine.ipdb_link.blank?)
    = link_to "IPDB", "http://ipdb.org/search.pl?name=#{lmx.machine.name};qh=checked;searchtype=advanced"
    = link_to image_tag( 'open-in-new-black.png', :alt => 'open in new window', :class => 'external_machine_link_icon'), "http://ipdb.org/search.pl?name=#{lmx.machine.name};qh=checked;searchtype=advanced", :target => '_blank'
  - else
    = link_to "IPDB", lmx.machine.ipdb_link, :target => '_blank'
    = link_to image_tag( 'open-in-new-black.png', :alt => 'open in new window', :class => 'external_machine_link_icon'), lmx.machine.ipdb_link, :target => '_blank'

app/views/location_machine_xrefs/_list_machine.html.haml
%div.machine_name_container
  %span{:class => ["bold sans font22 machine_name", ("w_100" unless user_signed_in?)]}
    #{lmx.machine.name}
    %span.machine_year_man #{lmx.machine.year_and_manufacturer}
  - if user_signed_in?
    = render :partial => 'location_machine_xrefs/remove_machine', :locals => {:lmx => lmx}

app/views/location_machine_xrefs/_pintips.html.haml
- if (!lmx.machine.opdb_id.blank?)
  .external_machine_link
    = link_to "PinTips", "http://pintips.net/opdb/#{lmx.machine.opdb_id}", :target => '_blank'
    =link_to image_tag( 'open-in-new-black.png', :alt => 'open in new window', :class => 'external_machine_link_icon'), "http://pintips.net/opdb/#{lmx.machine.opdb_id}", :target => '_blank'

app/views/location_machine_xrefs/_remove_machine.html.haml
= button_to location_machine_xref_path(:id => lmx.id), :id => "remove_machine_#{lmx.id}", :method => 'delete', :remote => true, :class => "remove_machine_button" do
  =image_tag('icons/trash-can-outline.svg', alt: 'Remove Machine')

:javascript
  $('#remove_machine_#{lmx.id}').click(function () {
    if (confirm("Remove this machine?")) {
      $('#machine_lmx_#{lmx.id}').fadeOut('slow', function() {
        updateLocationUpdatedText(#{lmx.location_id});
        $('#gm_machines_#{lmx.location_id}').load('/locations/#{lmx.location_id}/render_machine_names_for_infowindow', function() {
          $('#show_machines_location_count_#{lmx.location_id}').load('/locations/#{lmx.location_id}/render_machines_count', function() {});
        });
      });

      $(this).callRemote();
    }
    return false;
  });

app/views/location_machine_xrefs/_update_machine_condition.html.haml
- if user_signed_in?
  %div[lmx, :machine_condition]
    =image_tag("icons/comment-text.svg", :alt => "Leave a Comment", :class => "machine_comment_icon")
    %div.add_condition Add machine comment
  %div[lmx, :machine_condition_edit]{:style => 'display:none'}
    = form_tag update_machine_condition_location_machine_xrefs_path(:action => 'update_machine_condition', :id => lmx.id), :id => "update_machine_condition_#{lmx.id}", :class => "update_machine_condition_lmx", :method => 'get' do
      = hidden_field_tag :id, lmx.id
      = text_area_tag "new_machine_condition_#{lmx.id}", '', :cols => 20, :rows => 3, :class => 'edit_mode', :placeholder => '(note: if this machine is gone, please just remove it. no need to leave a comment saying it is gone)'
      %div.brightpurple{:style => "margin: 5px;line-height: 16px;"}
        %span.bold Operators:
        if you've fixed an issue, please leave a comment saying so. But please do not comment simply to "whitewash" people's comments that bother you. This is getting to be an issue.
      %br/
      = submit_tag 'Save', :id => "save_machine_condition_#{lmx.id}", :class => "save_button"
    = submit_tag 'Cancel', :id => "cancel_machine_condition_#{lmx.id}", :class => "cancel_button"


:javascript
  $('#update_machine_condition_#{lmx.id}').submit(function () {

    var form = $(this);
    $.get(form.attr('action'), form.serialize(), function (data) {
      $('#show_conditions_lmx_#{lmx.id}').load('/location_machine_xrefs/#{lmx.id}/render_machine_conditions');
      updateLocationUpdatedText(#{lmx.location_id});
    });
    $('#update_machine_condition_#{lmx.id} #new_machine_condition_#{lmx.id}').val('');

    return false;
  });

  $('#cancel_machine_condition_#{lmx.id}, #machine_condition_lmx_#{lmx.id}').click(function () {
    $('#machine_condition_edit_lmx_#{lmx.id}').toggle();
    $('#machine_condition_lmx_#{lmx.id}').toggle();
  });